force-app/main/default/objects/Integration_Files__c/Integration_Files__c.object-meta.xml
<CustomObject>
    <label>Integration Files</label>
    <nameField>
        <displayFormat>File-{0000}</displayFormat>
        <label>Integration Files Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Files__c/fields/Mass_Upload_CSV__c.field-meta.xml
<CustomField>
    <fullName>Mass_Upload_CSV__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mass Upload CSV</label>
    <referenceTo>Mass_Upload_CSV__c</referenceTo>
    <relationshipLabel>Integration Files</relationshipLabel>
    <relationshipName>Integration_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Files__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Inprocess</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Files__c/fields/Success_Records__c.field-meta.xml
<CustomField>
    <fullName>Success_Records__c</fullName>
    <formula>Mass_Upload_CSV__r.Success_records__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Success Records</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_Files__c/fields/Total_Records__c.field-meta.xml
<CustomField>
    <fullName>Total_Records__c</fullName>
    <formula>Mass_Upload_CSV__r.Total_records__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Records</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_Files__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auto</fullName>
                <default>true</default>
                <label>Auto</label>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/Mass_Upload_CSV__c.object-meta.xml
<CustomObject>
    <label>Mass Upload CSV</label>
    <nameField>
        <label>Mass Upload CSV Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mass Upload CSVs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/CSV_fields__c.field-meta.xml
<CustomField>
    <fullName>CSV_fields__c</fullName>
    <label>CSV fields</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>File_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Profit_Center__r</fullName>
            </value>
            <value>
                <fullName>Sales_Org__r</fullName>
            </value>
            <value>
                <fullName>Dc</fullName>
            </value>
            <value>
                <fullName>Div</fullName>
            </value>
            <value>
                <fullName>SKU_Code__r</fullName>
            </value>
            <value>
                <fullName>UOM__c</fullName>
            </value>
            <value>
                <fullName>Type__c</fullName>
            </value>
            <value>
                <fullName>Distributor_Code__r</fullName>
            </value>
            <value>
                <fullName>Depot_Code__r</fullName>
            </value>
            <value>
                <fullName>Combination_Key__c</fullName>
            </value>
            <value>
                <fullName>Sales_Deduction_LC__c</fullName>
            </value>
            <value>
                <fullName>Sales_Deduction_USD__c</fullName>
            </value>
            <value>
                <fullName>E2E_Cost_LC__c</fullName>
            </value>
            <value>
                <fullName>E2E_Cost_USD__c</fullName>
            </value>
            <value>
                <fullName>E2E_Cost_UPC9_LC__c</fullName>
            </value>
            <value>
                <fullName>E2E_Cost_UPC9_USD__c</fullName>
            </value>
            <value>
                <fullName>E2E_Cost_MBEW_LC__c</fullName>
            </value>
            <value>
                <fullName>E2E_Cost_MBEW_USD__c</fullName>
            </value>
            <value>
                <fullName>Rebate_Code__c</fullName>
            </value>
            <value>
                <fullName>Rebate_USD__c</fullName>
            </value>
            <value>
                <fullName>Rebate_LC__c</fullName>
            </value>
            <value>
                <fullName>Rebate__c</fullName>
            </value>
            <value>
                <fullName>Discount_LC__c</fullName>
            </value>
            <value>
                <fullName>Discount_USD__c</fullName>
            </value>
            <value>
                <fullName>Discount__c</fullName>
            </value>
            <value>
                <fullName>Additional_Discount_LC__c</fullName>
            </value>
            <value>
                <fullName>Additional_Discount_USD__c</fullName>
            </value>
            <value>
                <fullName>Additional_Discount__c</fullName>
            </value>
            <value>
                <fullName>PLN_LC__c</fullName>
            </value>
            <value>
                <fullName>PLN_USD__c</fullName>
            </value>
            <value>
                <fullName>End_Date__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/Error_records__c.field-meta.xml
<CustomField>
    <fullName>Error_records__c</fullName>
    <label>Error records</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <label>File Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SalesDeduction</fullName>
            </value>
            <value>
                <fullName>E2ECost</fullName>
            </value>
            <value>
                <fullName>E2ECostUPC9</fullName>
            </value>
            <value>
                <fullName>E2ECostMBEW</fullName>
            </value>
            <value>
                <fullName>Rebate</fullName>
            </value>
            <value>
                <fullName>AdditionalDiscount</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>PLN</fullName>
            </value>
            <value>
                <fullName>UOMConversion</fullName>
            </value>
            <value>
                <fullName>USDExchangeRate</fullName>
            </value>
            <value>
                <fullName>PLNCustomer</fullName>
            </value>
            <value>
                <fullName>RebateCustomer</fullName>
            </value>
            <value>
                <fullName>E2E UPC9</fullName>
                <isActive>false</isActive>
                <label>E2E UPC9</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/isAttachment__c.field-meta.xml
<CustomField>
    <fullName>isAttachment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isAttachment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auto</fullName>
                <default>true</default>
                <label>Auto</label>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Insert</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Upsert</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Mass_Upload_CSV__c</referenceTo>
    <relationshipLabel>Mass Upload CSVs</relationshipLabel>
    <relationshipName>Mass_Upload_CSVs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/Seperator__c.field-meta.xml
<CustomField>
    <fullName>Seperator__c</fullName>
    <label>Seperator</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Inprogress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/Success_records__c.field-meta.xml
<CustomField>
    <fullName>Success_records__c</fullName>
    <label>Success records</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/Total_records__c.field-meta.xml
<CustomField>
    <fullName>Total_records__c</fullName>
    <label>Total records</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/Upload_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Upload_Date_Time__c</fullName>
    <label>Upload Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/Upsert_Key__c.field-meta.xml
<CustomField>
    <fullName>Upsert_Key__c</fullName>
    <externalId>true</externalId>
    <label>Upsert Key</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/recordTypes/Original.recordType-meta.xml
<RecordType>
    <fullName>Original</fullName>
    <active>true</active>
    <label>Original</label>
</RecordType>

force-app/main/default/objects/MassUploadExternalIdRecords__c/MassUploadExternalIdRecords__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Use to Map External Id of Objects used while uploading csv files through MASS Upload CSV Module</description>
    <label>MassUploadExternalIdRecords</label>
</CustomObject>

force-app/main/default/objects/MassUploadExternalIdRecords__c/fields/CSVFields__c.field-meta.xml
<CustomField>
    <fullName>CSVFields__c</fullName>
    <label>CSVFields</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MassUploadExternalIdRecords__c/fields/DataType__c.field-meta.xml
<CustomField>
    <fullName>DataType__c</fullName>
    <label>DataType</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MassUploadExternalIdRecords__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <label>ExternalId</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MassUploadExternalIdRecords__c/fields/FieldUseInCombinationKey__c.field-meta.xml
<CustomField>
    <fullName>FieldUseInCombinationKey__c</fullName>
    <description>Field used in combination Key by semicolon separator</description>
    <label>FieldUseInCombinationKey</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MassUploadExternalIdRecords__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <label>Length</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MassUploadExternalIdRecords__c/fields/TypeApiName__c.field-meta.xml
<CustomField>
    <fullName>TypeApiName__c</fullName>
    <label>TypeApiName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MassUploadCSVTriggerTest.cls
@isTest(SeeAllData=false)
public class MassUploadCSVTriggerTest {
    @isTest
    public static void testSetupmassCSV(){
        
        Id MassUploadRecordTypeId = [SELECT Id, Name, DeveloperName, SobjectType, IsActive FROM RecordType where SobjectType='Mass_Upload_CSV__c' and Name='Original' limit 1].Id;
        
        insert new Trigger_Settings__c(Name ='MassUploadCSVTrigger', IsActive__c = true , ObjectName__c = 'Mass_Upload_CSV__c');
        
        MassUploadCSVTriggerHandler mucsv = new  MassUploadCSVTriggerHandler();
        Map<Id, SObject> oldItems = new Map<Id, SObject>();
        Map<Id,Sobject> newItems = new Map<Id,Sobject>();
        Map<String,ContentVersion> mapContentversion=new Map<String,ContentVersion>();
        ReadAndSplitAttachment rns = new ReadAndSplitAttachment(newItems);
        List <Mass_Upload_CSV__c> massCSV = new List<Mass_Upload_CSV__c>();
        
        MassUploadExternalIdRecords__c ext = new MassUploadExternalIdRecords__c();
        ext.Name='Price_Block_Margin_Matrix__c(SalesDed)';
        ext.Type__c='SalesDeduction';
        ext.FieldUseInCombinationKey__c='Profit_Center__r;Sales_Org__r;Dc;Div;SKU_Code__r;UOM__c;Type__c';
        ext.DataType__c='';
        ext.TypeApiName__c='Type__c';
        ext.ExternalId__c='Combination_Key__c';
        ext.ObjectName__c='Price_Block_Margin_Matrix__c';
        ext.CSVFields__c='Profit_Center__r;Sales_Org__r;Dc;Div;SKU_Code__r;UOM__c;Sales_Deduction_LC__c;Sales_Deduction_USD__c;Start_Date__c;End_Date__c';
        ext.Length__c=null;
        insert ext;
              
        MassUploadExternalIdRecords__c ext1 = new MassUploadExternalIdRecords__c();
        ext1.Name='SKU_Code__r';
        ext1.FieldUseInCombinationKey__c='Sales_Org__r;Dc;Div;SKU_Code__r';
        ext1.DataType__c='Lookup';
        ext1.TypeApiName__c='';
        ext1.ExternalId__c='Combination_Key__c';
        ext1.ObjectName__c='SKU__c';
        ext1.CSVFields__c='';
        ext1.Length__c=18;
        insert ext1;
        
        MassUploadExternalIdRecords__c ext2 = new MassUploadExternalIdRecords__c();
        ext2.Name='Profit_Center__r';
        ext2.Type__c='';
        ext2.FieldUseInCombinationKey__c='Sales_Org__r;Profit_Center__r';
        ext2.DataType__c='Lookup';
        ext2.TypeApiName__c='';
        ext2.ExternalId__c='Combination_Key__c';
        ext2.ObjectName__c='Profit_Center__c';
        ext2.CSVFields__c='';
        ext2.Length__c=null;
        insert ext2;
        
        MassUploadExternalIdRecords__c ext7 = new MassUploadExternalIdRecords__c();
        ext7.Name='Sales_Org__r';
        ext7.Type__c='';
        ext7.FieldUseInCombinationKey__c='Sales_Org__r';
        ext7.DataType__c='Lookup';
        ext7.TypeApiName__c='';
        ext7.ExternalId__c='Sales_Org_Code__c';
        ext7.ObjectName__c='Sales_Org__c';
        ext7.CSVFields__c='';
        ext7.Length__c=null;
        insert ext7;
        
        MassUploadExternalIdRecords__c ext3 = new MassUploadExternalIdRecords__c();
        ext3.Name='Sales_Deduction_LC__c';
        ext3.DataType__c='Number';
        insert ext3;
        
        MassUploadExternalIdRecords__c ext4 = new MassUploadExternalIdRecords__c();
        ext4.Name='Sales_Deduction_USD__c';
        ext4.DataType__c='Number';
        insert ext4;
        
        MassUploadExternalIdRecords__c ext5 = new MassUploadExternalIdRecords__c();
        ext5.Name='UOM__c';
        ext5.DataType__c='Text';
        insert ext5;
        
        MassUploadExternalIdRecords__c ext6 = new MassUploadExternalIdRecords__c();
        ext6.Name='End_Date__c';
        ext6.DataType__c='Date';
        insert ext6;
        
        MassUploadExternalIdRecords__c ext8 = new MassUploadExternalIdRecords__c();
        ext8.Name='End_Date__c';
        ext8.DataType__c='Date';
        insert ext8;
        
        String str = 'Profit Center;Sales Org;Dc;Div;SKU Code;UOM;Sales Deduction_LC;Sales Deduction USD;Start Date;End Date\nLA0005;5100;20;10;856010;KG;11;0.58;30042022;31032023\nLA0005;5100;20;60;856010;KG;11;0.58;30042022;31032023';
        ContentVersion content=new Contentversion();
        Blob b=Blob.valueOf(str); 
        content.title='SalesDeduction';
        content.PathOnClient ='test'; 
        content.versiondata=b; 
        content.IsMajorVersion=true;
        insert content;
        
        Mass_Upload_CSV__c mass1=new Mass_Upload_CSV__c();
        mass1.Comments__c='test';
        mass1.CSV_fields__c='Profit_Center__r; Sales_Org__r; Dc; Div; SKU_Code__r; UOM__c; Sales_Deduction_LC__c; Sales_Deduction_USD__c; Start_Date__c; End_Date__c';
        mass1.Error_records__c=50;
        mass1.File_Name__c='SalesDeduction';
        mass1.File_Type__c='SalesDeduction';
        mass1.isAttachment__c=true;
        mass1.Mode__c='Auto';
        mass1.Object_Name__c='Price_Block_Margin_Matrix__c';
        mass1.Operation__c='Insert';
        mass1.Parent__c=mass1.Id;
        mass1.Seperator__c=';';
        mass1.Status__c='Inprogress';
        mass1.Success_records__c=100;
        mass1.Total_records__c=5000;
        mass1.Upload_Date_Time__c=datetime.newInstance(2022, 9, 15, 12, 30, 0);
       // mass1.Upsert_Key__c='abcs1234';
        mass1.RecordTypeId=MassUploadRecordTypeId;
        insert mass1;
        
        Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:content.Id].ContentDocumentId;
        
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = mass1.Id;
        cdl.ContentDocumentId = conDocId;   
        cdl.Visibility='AllUsers';
        cdl.ShareType = 'I';
        Insert cdl;   
        
        Integration_Files__c file=new Integration_Files__c();
        file.Status__c='Completed';
        file.Mass_Upload_CSV__c=mass1.id;
        insert file;
        
        Test.startTest();
        mucsv.beforeDelete(oldItems);
        mucsv.afterUndelete(oldItems);
        mucsv.afterDelete(oldItems, newItems);
        rns.divideCSV(newItems, mapContentversion);
        System.enqueueJob(rns);
       
        Test.stopTest();

    }
    
     @isTest
    public static void testSetupmassCSV2(){
    
    }
 
}