force-app/main/default/objects/Mass_Upload_CSV__c/Mass_Upload_CSV__c.object-meta.xml
<CustomObject>
    <label>Mass Upload CSV</label>
    <nameField>
        <label>Mass Upload CSV Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mass Upload CSVs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/isAttachment__c.field-meta.xml
<CustomField>
    <fullName>isAttachment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isAttachment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Inprogress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/recordTypes/Original.recordType-meta.xml
<RecordType>
    <fullName>Original</fullName>
    <active>true</active>
    <label>Original</label>
</RecordType>

force-app/main/default/classes/ContentVersionTriggerHelperTest.cls
@isTest(SeeAllData=false)
public class ContentVersionTriggerHelperTest {
    @isTest
    public static void testContentVersionTriggerHelper(){
        
        Id MassUploadRecordTypeId = [SELECT Id, Name, DeveloperName, SobjectType, IsActive FROM RecordType where SobjectType='Mass_Upload_CSV__c' and Name='Original' limit 1].Id;
        system.debug('MassUploadRecordTypeId==>'+MassUploadRecordTypeId);
        
        insert new Trigger_Settings__c(Name ='MassUploadCSVTrigger' , IsActive__c = true , ObjectName__c = 'Mass_Upload_CSV__c');   
        
        String str = 'Profit Center;Sales Org;Dc;Div;SKU Code;UOM;Sales Deduction_LC;Sales Deduction USD;Start Date;End Date\nLA0005;5100;20;10;000000000000856010;KG;11;0.58;30042022;31032023';
        ContentVersion content=new Contentversion(); 
        content.title='SalesDeduction';
        content.PathOnClient ='test';
        // user  id= UserInfo.getUserId();
        Blob b=Blob.valueOf(str); 
        content.versiondata=b; 
        insert content;
        system.debug('content==>'+content);
        
        List<ContentVersion> contentId=[Select ContentDocumentId from ContentVersion where ID=:content.Id];
        System.debug('contentId Test==>'+contentId);
        
        
        List<String> contdocIds = new List<String>();
        for(ContentVersion contvar:contentId)
        {
            
            contdocIds.add(contvar.ContentDocumentId);
        }
        System.debug('contdocIds Test==>'+contdocIds);
        
        List<ContentDocumentLink> contentDocumentsLink=[select id,ContentDocumentId,LinkedEntityId from ContentDocumentLink where ContentDocumentId IN:contdocIds];
        System.debug('ContentDocumentLink Test==>'+contentDocumentsLink);
        
        List<String> MassUploadIds=new List<String>();
        for(ContentDocumentLink linkId :contentDocumentsLink)
        {
            MassUploadIds.add(linkId.LinkedEntityId);
        }
        System.debug('contentLink Test id is' +MassUploadIds);
        
        List<Mass_Upload_CSV__c> massUploadCSVs = [SELECT Id,isAttachment__c,Status__c FROM Mass_Upload_CSV__c WHERE Id In:MassUploadIds];
        system.debug('massUploadCSVs==>'+massUploadCSVs);
        Map<Id,SObject> massuploadmap = new Map<Id,SObject>();
        for(Mass_Upload_CSV__c masscsv:massUploadCSVs)
        {
            massuploadmap.put(masscsv.Id,masscsv);
        }
        
        Test.startTest();
        ContentVersionTriggerHelper cvs = new ContentVersionTriggerHelper();
        ContentVersionTriggerHelper.updateMassUploadCSV(massuploadmap);
        Grz_TestDataFactory.createContentDocument(true);
        
        Test.stopTest();
        
    } 
  
}