force-app/main/default/objects/Mass_Upload_CSV__c/Mass_Upload_CSV__c.object-meta.xml
<CustomObject>
    <label>Mass Upload CSV</label>
    <nameField>
        <label>Mass Upload CSV Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mass Upload CSVs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/CSV_fields__c.field-meta.xml
<CustomField>
    <fullName>CSV_fields__c</fullName>
    <label>CSV fields</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>File_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Profit_Center__r</fullName>
            </value>
            <value>
                <fullName>Sales_Org__r</fullName>
            </value>
            <value>
                <fullName>Dc</fullName>
            </value>
            <value>
                <fullName>Div</fullName>
            </value>
            <value>
                <fullName>SKU_Code__r</fullName>
            </value>
            <value>
                <fullName>UOM__c</fullName>
            </value>
            <value>
                <fullName>Type__c</fullName>
            </value>
            <value>
                <fullName>Distributor_Code__r</fullName>
            </value>
            <value>
                <fullName>Depot_Code__r</fullName>
            </value>
            <value>
                <fullName>Combination_Key__c</fullName>
            </value>
            <value>
                <fullName>Sales_Deduction_LC__c</fullName>
            </value>
            <value>
                <fullName>Sales_Deduction_USD__c</fullName>
            </value>
            <value>
                <fullName>E2E_Cost_LC__c</fullName>
            </value>
            <value>
                <fullName>E2E_Cost_USD__c</fullName>
            </value>
            <value>
                <fullName>E2E_Cost_UPC9_LC__c</fullName>
            </value>
            <value>
                <fullName>E2E_Cost_UPC9_USD__c</fullName>
            </value>
            <value>
                <fullName>E2E_Cost_MBEW_LC__c</fullName>
            </value>
            <value>
                <fullName>E2E_Cost_MBEW_USD__c</fullName>
            </value>
            <value>
                <fullName>Rebate_Code__c</fullName>
            </value>
            <value>
                <fullName>Rebate_USD__c</fullName>
            </value>
            <value>
                <fullName>Rebate_LC__c</fullName>
            </value>
            <value>
                <fullName>Rebate__c</fullName>
            </value>
            <value>
                <fullName>Discount_LC__c</fullName>
            </value>
            <value>
                <fullName>Discount_USD__c</fullName>
            </value>
            <value>
                <fullName>Discount__c</fullName>
            </value>
            <value>
                <fullName>Additional_Discount_LC__c</fullName>
            </value>
            <value>
                <fullName>Additional_Discount_USD__c</fullName>
            </value>
            <value>
                <fullName>Additional_Discount__c</fullName>
            </value>
            <value>
                <fullName>PLN_LC__c</fullName>
            </value>
            <value>
                <fullName>PLN_USD__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <label>File Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SalesDeduction</fullName>
            </value>
            <value>
                <fullName>E2ECost</fullName>
            </value>
            <value>
                <fullName>E2ECostUPC9</fullName>
            </value>
            <value>
                <fullName>E2ECostMBEW</fullName>
            </value>
            <value>
                <fullName>Rebate</fullName>
            </value>
            <value>
                <fullName>AdditionalDiscount</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>PLN</fullName>
            </value>
            <value>
                <fullName>UOMConversion</fullName>
            </value>
            <value>
                <fullName>USDExchangeRate</fullName>
            </value>
            <value>
                <fullName>PLNCustomer</fullName>
            </value>
            <value>
                <fullName>RebateCustomer</fullName>
            </value>
            <value>
                <fullName>E2E UPC9</fullName>
                <isActive>false</isActive>
                <label>E2E UPC9</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auto</fullName>
                <default>true</default>
                <label>Auto</label>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Inprogress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/recordTypes/Original.recordType-meta.xml
<RecordType>
    <fullName>Original</fullName>
    <active>true</active>
    <label>Original</label>
</RecordType>

force-app/main/default/objects/MassUploadExternalIdRecords__c/MassUploadExternalIdRecords__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Use to Map External Id of Objects used while uploading csv files through MASS Upload CSV Module</description>
    <label>MassUploadExternalIdRecords</label>
</CustomObject>

force-app/main/default/objects/MassUploadExternalIdRecords__c/fields/CSVFields__c.field-meta.xml
<CustomField>
    <fullName>CSVFields__c</fullName>
    <label>CSVFields</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MassUploadExternalIdRecords__c/fields/DataType__c.field-meta.xml
<CustomField>
    <fullName>DataType__c</fullName>
    <label>DataType</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MassUploadExternalIdRecords__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <label>ExternalId</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MassUploadExternalIdRecords__c/fields/FieldUseInCombinationKey__c.field-meta.xml
<CustomField>
    <fullName>FieldUseInCombinationKey__c</fullName>
    <description>Field used in combination Key by semicolon separator</description>
    <label>FieldUseInCombinationKey</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MassUploadExternalIdRecords__c/fields/isRecordType__c.field-meta.xml
<CustomField>
    <fullName>isRecordType__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isRecordType</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MassUploadExternalIdRecords__c/fields/TypeApiName__c.field-meta.xml
<CustomField>
    <fullName>TypeApiName__c</fullName>
    <label>TypeApiName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharePointDetails__c/SharePointDetails__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SharePointDetails</label>
</CustomObject>

force-app/main/default/objects/SharePointDetails__c/fields/Get_CSV_File_URL__c.field-meta.xml
<CustomField>
    <fullName>Get_CSV_File_URL__c</fullName>
    <label>Get CSV File URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/BatchGetCSVContent.cls
public with sharing class BatchGetCSVContent implements Database.Batchable<String>{
    String  folderName = 'folder1';
    public BatchGetCSVContent(String folderName){
        folderName = folderName;
    }

    public Iterable<String> start(Database.BatchableContext bc){
        List<String> fileNames = new List<String>();
        fileNames = ConnectToSharePoint.readFilesName(folderName);
        return fileNames;
    }
  
    public void execute(Database.BatchableContext bc, List<String> fileNames){
        String filname = fileNames[0]; 
        String csvBody = csvContent(this.folderName,filname);
        Blob content = Blob.valueOf(csvBody);
        Mass_Upload_CSV__c massupload = createMassUpload('SalesDeduction'); //TODO: Dyanamic Type from fileName
        createFiles(massupload,content);

    }
  
    public void finish(Database.BatchableContext bc){
    }

    public String csvContent(String folderName,String fileName){
        String accessToken = ConnectToSharePoint.authentication();
        SharePointDetails__c sharepointDetail = ConnectToSharePoint.getSharePointdetails();
        Http https = new Http();
        HttpRequest request = new HttpRequest();
        String authorizationHeader = 'Bearer '+accessToken;
        String appendFolder = sharepointDetail.Get_CSV_File_URL__c + folderName+'/'+fileName+'\')'+'/$value';
        request.setendPoint(appendFolder);
        request.setMethod('GET');
        request.setHeader('Accept', 'application/json;odata=verbose');
        request.setHeader('Authorization',authorizationHeader);
        httpResponse response = https.send(request);
        System.debug('Body Files'+response.getbody());
        // String csvbody = response.getbody(); TODO: Reponse from API
        String csvbody = 'Profit Center,Sales Org,Dc,Div,SKU Code,UOM ,Sales Deduction LC,Sales Deduction USD,Start Date, End Date \nLA0005,5100,20,10,000000000000856010,KG,11,0.58,30042022,31032023\nLA0005,5100,20,10,000000000000856083,KG,12,0.68,30042022,31032023\nLA0005,5100,20,10,000000000000854052,KG,13,1,30042022,31032023\nLA0005,5100,20,60,000000000000854053,KG,14,1,30042022,31032023\nLA0005,5100,20,60,000000000000720502,KG,15,12,30042022,31032023';
        return csvbody;
    }

    public void linkFilesToMassUpload(){

    }
    public  Mass_Upload_CSV__c createMassUpload(String type){
        MassUploadExternalIdRecords__c massUploadExternalIdRecords = [select Id,Name,DataType__c,ExternalId__c,ObjectName__c,FieldUseInCombinationKey__c,isRecordType__c,Type__c,CSVFields__c,TypeApiName__c from MassUploadExternalIdRecords__c where Type__c =:type limit 1];   
        Id MassUploadSplitRecordTypeId = [SELECT Id, Name, DeveloperName, SobjectType, IsActive FROM RecordType where SobjectType='Mass_Upload_CSV__c' and Name='Original' limit 1].Id;

        Mass_Upload_CSV__c massupload = new Mass_Upload_CSV__c();
        massupload.Name = type;
        massupload.CSV_fields__c = massUploadExternalIdRecords.CSVFields__c;
        massupload.File_Name__c = type;
        massupload.File_Type__c = type;
        massupload.Mode__c = 'Auto';
        massupload.Object_Name__c = massUploadExternalIdRecords.ObjectName__c;
        massupload.Status__c = 'Draft';
        massupload.RecordTypeId = MassUploadSplitRecordTypeId;
        insert massupload;
        return massupload;
    }
    public  void createFiles(Mass_Upload_CSV__c massupload,Blob content){    
        ContentVersion contentV = new ContentVersion();
        contentV.VersionData=content;
        contentV.Title=massupload.File_Name__c;
        contentV.PathOnClient=massupload.File_Name__c +'.'+'csv';
        contentV.IsMajorVersion=true;
        insert contentV;
        
        Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:contentV.Id].ContentDocumentId;
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = massupload.Id;
        cdl.ContentDocumentId = conDocId;
        Insert cdl;
    }

}