force-app/main/default/objects/Mass_Upload_CSV__c/Mass_Upload_CSV__c.object-meta.xml
<CustomObject>
    <label>Mass Upload CSV</label>
    <nameField>
        <label>Mass Upload CSV Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mass Upload CSVs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/CSV_fields__c.field-meta.xml
<CustomField>
    <fullName>CSV_fields__c</fullName>
    <label>CSV fields</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>File_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Profit_Center__r</fullName>
            </value>
            <value>
                <fullName>Sales_Org__r</fullName>
            </value>
            <value>
                <fullName>Dc</fullName>
            </value>
            <value>
                <fullName>Div</fullName>
            </value>
            <value>
                <fullName>SKU_Code__r</fullName>
            </value>
            <value>
                <fullName>UOM__c</fullName>
            </value>
            <value>
                <fullName>Type__c</fullName>
            </value>
            <value>
                <fullName>Distributor_Code__r</fullName>
            </value>
            <value>
                <fullName>Depot_Code__r</fullName>
            </value>
            <value>
                <fullName>Combination_Key__c</fullName>
            </value>
            <value>
                <fullName>Sales_Deduction_LC__c</fullName>
            </value>
            <value>
                <fullName>Sales_Deduction_USD__c</fullName>
            </value>
            <value>
                <fullName>E2E_Cost_LC__c</fullName>
            </value>
            <value>
                <fullName>E2E_Cost_USD__c</fullName>
            </value>
            <value>
                <fullName>E2E_Cost_UPC9_LC__c</fullName>
            </value>
            <value>
                <fullName>E2E_Cost_UPC9_USD__c</fullName>
            </value>
            <value>
                <fullName>E2E_Cost_MBEW_LC__c</fullName>
            </value>
            <value>
                <fullName>E2E_Cost_MBEW_USD__c</fullName>
            </value>
            <value>
                <fullName>Rebate_Code__c</fullName>
            </value>
            <value>
                <fullName>Rebate_USD__c</fullName>
            </value>
            <value>
                <fullName>Rebate_LC__c</fullName>
            </value>
            <value>
                <fullName>Rebate__c</fullName>
            </value>
            <value>
                <fullName>Discount_LC__c</fullName>
            </value>
            <value>
                <fullName>Discount_USD__c</fullName>
            </value>
            <value>
                <fullName>Discount__c</fullName>
            </value>
            <value>
                <fullName>Additional_Discount_LC__c</fullName>
            </value>
            <value>
                <fullName>Additional_Discount_USD__c</fullName>
            </value>
            <value>
                <fullName>Additional_Discount__c</fullName>
            </value>
            <value>
                <fullName>PLN_LC__c</fullName>
            </value>
            <value>
                <fullName>PLN_USD__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/Error_records__c.field-meta.xml
<CustomField>
    <fullName>Error_records__c</fullName>
    <label>Error records</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <label>File Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SalesDeduction</fullName>
            </value>
            <value>
                <fullName>E2ECost</fullName>
            </value>
            <value>
                <fullName>E2ECostUPC9</fullName>
            </value>
            <value>
                <fullName>E2ECostMBEW</fullName>
            </value>
            <value>
                <fullName>Rebate</fullName>
            </value>
            <value>
                <fullName>AdditionalDiscount</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>PLN</fullName>
            </value>
            <value>
                <fullName>UOMConversion</fullName>
            </value>
            <value>
                <fullName>USDExchangeRate</fullName>
            </value>
            <value>
                <fullName>PLNCustomer</fullName>
            </value>
            <value>
                <fullName>RebateCustomer</fullName>
            </value>
            <value>
                <fullName>E2E UPC9</fullName>
                <isActive>false</isActive>
                <label>E2E UPC9</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/isAttachment__c.field-meta.xml
<CustomField>
    <fullName>isAttachment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isAttachment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auto</fullName>
                <default>true</default>
                <label>Auto</label>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Insert</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Upsert</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Mass_Upload_CSV__c</referenceTo>
    <relationshipLabel>Mass Upload CSVs</relationshipLabel>
    <relationshipName>Mass_Upload_CSVs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/Seperator__c.field-meta.xml
<CustomField>
    <fullName>Seperator__c</fullName>
    <label>Seperator</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Inprogress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/Success_records__c.field-meta.xml
<CustomField>
    <fullName>Success_records__c</fullName>
    <label>Success records</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/Total_records__c.field-meta.xml
<CustomField>
    <fullName>Total_records__c</fullName>
    <label>Total records</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/Upload_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Upload_Date_Time__c</fullName>
    <label>Upload Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/fields/Upsert_Key__c.field-meta.xml
<CustomField>
    <fullName>Upsert_Key__c</fullName>
    <externalId>true</externalId>
    <label>Upsert Key</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Mass_Upload_CSV__c/recordTypes/Split.recordType-meta.xml
<RecordType>
    <fullName>Split</fullName>
    <active>true</active>
    <label>Split</label>
</RecordType>

force-app/main/default/classes/MassUploadProcessAttachmentBatch.cls
public class MassUploadProcessAttachmentBatch implements Database.Batchable<sObject>, Database.Stateful {
	public List<String> contentVersionIds;
	public Mass_Upload_CSV__c massupload;

	public MassUploadProcessAttachmentBatch(List<String> contentVersionIds) {
		this.contentVersionIds = contentVersionIds;
	}

	public Database.QueryLocator start(Database.BatchableContext bc){
        System.debug('Inside Start Method==>'+this.contentVersionIds);
        List<String> cvtemp = this.contentVersionIds;
        return Database.getQueryLocator('SELECT Id, VersionData,ContentDocumentId,Title FROM ContentVersion WHERE Id IN:cvtemp');
    }

	public void execute(Database.BatchableContext bc, List<ContentVersion> contentVersionData){
        System.debug('Execute List==>'+contentVersionData);
        try {
            if(contentVersionData.size()>0){
                String contentVersionId=contentVersionData[0].id;
                ContentVersion contentvar=[SELECT Id,ContentDocumentId,Title,VersionData FROM ContentVersion WHERE Id =:contentVersionId];
                List<ContentDocumentLink> conDocLink = [SELECT Id,LinkedEntityId FROM ContentDocumentLink WHERE ContentDocumentId =:contentvar.ContentDocumentId];
                List<String> linkentityID= new List<String> ();
                for(ContentDocumentLink linkEId:conDocLink){
                    linkentityID.add(linkEId.LinkedEntityId);
                }
                massupload=[select Id,name,Comments__c,CSV_fields__c,Error_records__c,File_Name__c,File_Type__c,isAttachment__c,Mode__c,Object_Name__c,	Operation__c,Parent__c,Status__c,Success_records__c,Total_records__c,Upload_Date_Time__c,Upsert_Key__c,Seperator__c from Mass_Upload_CSV__c where Id IN:linkentityID limit 1];
                
                SplitString splitObj = new SplitString();
                String fileTypeName=massupload.File_Type__c.deleteWhitespace();
                if(contentvar.Title.contains(fileTypeName)){
                   list<String> csvFileds=massupload.CSV_fields__c.split(';');
                   List<String> csvbody=splitObj.safeSplit(contentvar.VersionData.toString(), '\n');
                   MassUploadProcessAttachmentBatchHelper.createRecords(csvbody,massupload,bc);
               }
            }
        } catch (Exception e) {
            massupload.Comments__c=e.getMessage();
            massupload.Status__c='Rejected';
	        update massupload;
            System.abortJob(bc.getJobId());
        }
    }

	public void finish(Database.BatchableContext bc){
        System.debug('Inside Finish Method');  
        Mass_Upload_CSV__c splitmassUploadCsv  = [select Id,Name,Parent__c,Error_records__c,Success_records__c,Total_records__c,Status__c,Comments__c from Mass_Upload_CSV__c where Id=:massupload.Id];
        String parentId = splitmassUploadCsv.Parent__c;
        Mass_Upload_CSV__c   parentMassUpload= [select ID,Name, Error_records__c,Success_records__c,Total_records__c,Status__c,Comments__c from Mass_Upload_CSV__c where id=:parentId];
        Integer totalSuccessCount = 0;
        Integer totalErrorCount = 0;
        Integer totalRecordsCount=0;
        Decimal successCount=0;
        Decimal errorCount=0;
        Decimal totalCount=0;
        List<Mass_Upload_CSV__c> allSplitMassupload=[select ID,Name, Error_records__c,Success_records__c,Parent__c,Total_records__c,Status__c,Comments__c from Mass_Upload_CSV__c where Parent__c=:ParentId];
        for(Mass_Upload_CSV__c split:allSplitMassupload){
            totalCount= !String.isEmpty(String.valueof(split.Total_records__c))  ? split.Total_records__c :0;            
            successCount= !String.isEmpty(String.valueof(split.Success_records__c))  ? split.Success_records__c :0;
            errorCount= !String.isEmpty(String.valueof(split.Error_records__c))  ? split.Error_records__c :0 ;
            parentMassUpload.Total_records__c = totalRecordsCount +totalCount +(!String.isEmpty(String.valueof(parentMassUpload.Total_records__c))  ? parentMassUpload.Total_records__c :0) ;  
            parentMassUpload.Success_records__c = totalSuccessCount +successCount+(!String.isEmpty(String.valueof(parentMassUpload.Success_records__c))  ? parentMassUpload.Success_records__c :0) ;      
            parentMassUpload.Error_records__c  = totalErrorCount +errorCount+(!String.isEmpty(String.valueof(parentMassUpload.Error_records__c))  ? parentMassUpload.Error_records__c :0) ;
            parentMassUpload.Status__c=split.Status__c;
            parentMassUpload.Comments__c=split.Comments__c; 
            }
        //parentMassUpload.Status__c='Completed';
         update parentMassUpload; 
    }

}